PERMISSION_MAP: dict[str, list[str]] = {
    "super_admin": [
        "manage_users", "view_users",
        "create_product", "edit_product", "delete_product", "view_products",
        "view_inventory", "adjust_stock", "record_damaged", "view_inventory_logs",
        "access_pos", "create_sale", "void_sale", "view_own_sales", "view_all_sales",
        "create_request", "approve_request", "reject_request",
        "execute_main_to_pos", "execute_pos_to_pos", "execute_pos_to_main",
        "direct_transfer", "view_transfers",
        "view_sales_reports", "view_inventory_reports", "view_financial_reports",
        "view_branch_reports", "view_cashier_reports",
        "view_all_audit_logs", "view_inventory_audit", "view_transfer_audit",
        "manage_system_settings", "view_system_settings",
    ],
    "admin": [
        "view_users",
        "create_product", "edit_product", "view_products",
        "view_inventory", "adjust_stock", "record_damaged", "view_inventory_logs",
        "access_pos", "create_sale", "void_sale", "view_own_sales", "view_all_sales",
        "create_request", "approve_request", "reject_request",
        "execute_main_to_pos", "execute_pos_to_pos", "execute_pos_to_main",
        "direct_transfer", "view_transfers",
        "view_sales_reports", "view_inventory_reports", "view_financial_reports",
        "view_branch_reports", "view_cashier_reports",
        "view_all_audit_logs", "view_inventory_audit", "view_transfer_audit",
        "view_system_settings",
    ],
    "general_manager": [
        "view_products",
        "view_inventory",
        "view_own_sales", "view_all_sales",
        "approve_request", "reject_request",
        "execute_main_to_pos", "execute_pos_to_pos", "execute_pos_to_main",
        "direct_transfer", "view_transfers",
        "view_sales_reports", "view_inventory_reports", "view_financial_reports",
        "view_branch_reports", "view_cashier_reports",
        "view_transfer_audit",
    ],
    "store_keeper": [
        "view_products",
        "view_inventory", "adjust_stock", "record_damaged", "view_inventory_logs",
        "create_request",
        "execute_main_to_pos", "view_transfers",
        "view_inventory_reports",
        "view_inventory_audit",
    ],
    "cashier": [
        "view_products",
        "access_pos", "create_sale", "view_own_sales",
        "create_request",
    ],
}

GLOBAL_ROLES = {"super_admin", "admin", "general_manager"}
